version: '3'

services:
  service-discovery:
    build:
      context: service-discovery
    image: tannerlankford/eureka-server:latest
    container_name: service-discovery
    environment:
      - USERNAME=${EUREKA_USERNAME}
      - PASSWORD=${EUREKA_PASSWORD}
    ports:
      - "8760:8760"

